#FROM ubuntu:latest
FROM debian:latest
ENV DEBIAN_FRONTEND=noninteractive
RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes
RUN apt-get update && apt-get upgrade
RUN apt-get install software-properties-common
#   Installing general prereqs
RUN apt-get update && apt-get install --no-install-recommends \
    ca-certificates \
    curl \
    jq \
    git \
    iputils-ping \
    libcurl4 \
    libunwind8 \
    libssl1.0 \
    wget \
    apt-transport-https \
    apt-utils \
  && rm -rf /var/lib/apt/lists/*

# #   Installing Python
# RUN apt-get update && apt-get install --no-install-recommends \
#     python3 \
#     python3-venv \
#     python3-pip \
#     python3-winrm \
#   && rm -rf /var/lib/apt/lists/*

#   Installing Ansible
# RUN apt-get update && apt-get install --no-install-recommends ansible && rm -rf /var/lib/apt/lists/*

#   Set Python venv
# RUN python3 -m venv venv
# RUN . venv/bin/activate
# RUN /venv/bin/pip install --upgrade pip

#   Install the Azure.azcollection
# RUN curl https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements.txt --output /tmp/azure-requirements.txt 
# RUN /venv/bin/pip install -r /tmp/azure-requirements.txt
#   # RUN ansible-galaxy collection install -r /tmp/azure-requirements.txt
#   # RUN /venv/bin/pip install "azure-cli==2.34.0"
# RUN /venv/bin/pip install -r lib/python3.10/site-packages/ansible_collections/azure/azcollection/requirements-azure.txt


# RUN pip install -r /tmp/azure-requirements.txt
# RUN ansible-galaxy collection install azure.azcollection --force

#   Microsoft PowerShell
# RUN wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
# RUN dpkg -i packages-microsoft-prod.deb
# RUN apt-get update
# RUN apt-get install powershell

#   Installing Azure CLI
RUN curl -LsS https://aka.ms/InstallAzureCLIDeb | bash && rm -rf /var/lib/apt/lists/*

#   Azure DevOps Agent
ARG TARGETARCH=amd64
ARG AGENT_VERSION=2.194.0
WORKDIR /azp
RUN if [ "$TARGETARCH" = "amd64" ]; then \
      AZP_AGENTPACKAGE_URL=https://vstsagentpackage.azureedge.net/agent/${AGENT_VERSION}/vsts-agent-linux-x64-${AGENT_VERSION}.tar.gz; \
    else \
      AZP_AGENTPACKAGE_URL=https://vstsagentpackage.azureedge.net/agent/${AGENT_VERSION}/vsts-agent-linux-${TARGETARCH}-${AGENT_VERSION}.tar.gz; \
    fi; \
    curl -LsS "$AZP_AGENTPACKAGE_URL" | tar -xz

# #   Hashicorp products (Packer & Terraform)
# RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
# RUN add-apt-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
# RUN apt-get update
# RUN apt-get install packer terraform

#   Clean up
RUN apt-get autoremove --purge
RUN apt-get clean

#   Set entrypoint
COPY ./start.sh .
RUN chmod +x start.sh
ENTRYPOINT [ "./start.sh" ]